modLoader="javafml"
loaderVersion="[43,)"
license="AGPL-3.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="synccraft"
version="${file.jarVersion}"
displayName="SyncCraft"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/qyl27/SyncCraft"
#logoFile="examplemod.png"
#credits=""
authors="qyl27"
displayTest="NONE"
description='''
For sync mods.
'''

[[dependencies.synccraft]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"
[[dependencies.synccraft]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"